// LIST
const SET_LIST = 'SET_LIST';
const ADD_ITEM = 'ADD_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const UPDATE_ITEM = 'UPDATE_ITEM';

export {
	SET_LIST,
	ADD_ITEM,
	DELETE_ITEM,
	UPDATE_ITEM,
}
